INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01001', '1', 'KAB. BADUNG ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01002', '1', 'KAB. BANGLI ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01003', '1', 'KAB. BULELENG ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01004', '0', 'KOTA DENPASAR ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01005', '1', 'KAB. GIANYAR ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01006', '1', 'KAB. JEMBRANA ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01007', '1', 'KAB. KARANGASEM ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01008', '1', 'KAB. KLUNGKUNG ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P01009', '1', 'KAB. TABANAN ', 'P01', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02001', '1', 'KAB. BANGKA ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02002', '1', 'KAB. BANGKA BARAT ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02003', '1', 'KAB. BANGKA SELATAN ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02004', '1', 'KAB. BANGKA TENGAH ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02005', '1', 'KAB. BELITUNG ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02006', '1', 'KAB. BELITUNG TIMUR ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P02007', '0', 'KOTA PANGKAL PINANG ', 'P02', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03001', '0', 'KOTA CILEGON ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03002', '1', 'KAB. LEBAK ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03003', '1', 'KAB. PANDEGLANG ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03004', '1', 'KAB. SERANG ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03005', '0', 'KOTA SERANG ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03006', '1', 'KAB. TANGERANG ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03007', '0', 'KOTA TANGERANG ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P03008', '0', 'KOTA TANGERANG SELATAN ', 'P03', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04001', '0', 'KOTA BENGKULU ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04002', '1', 'KAB. BENGKULU SELATAN ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04003', '1', 'KAB. BENGKULU TENGAH ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04004', '1', 'KAB. BENGKULU UTARA ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04005', '1', 'KAB. KAUR ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04006', '1', 'KAB. KEPAHIANG ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04007', '1', 'KAB. LEBONG ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04008', '1', 'KAB. MUKO MUKO ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04009', '1', 'KAB. REJANG LEBONG ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P04010', '1', 'KAB. SELUMA ', 'P04', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P05001', '1', 'KAB. BANTUL ', 'P05', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P05002', '1', 'KAB. GUNUNG KIDUL ', 'P05', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P05003', '1', 'KAB. KULON PROGO ', 'P05', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P05004', '1', 'KAB. SLEMAN ', 'P05', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P05005', '0', 'KOTA YOGYAKARTA ', 'P05', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P06001', '0', 'KOTA JAKARTA BARAT ', 'P06', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P06002', '0', 'KOTA JAKARTA PUSAT ', 'P06', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P06003', '0', 'KOTA JAKARTA SELATAN ', 'P06', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P06004', '0', 'KOTA JAKARTA TIMUR ', 'P06', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P06005', '0', 'KOTA JAKARTA UTARA ', 'P06', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P06006', '1', 'KAB. KEPULAUAN SERIBU ', 'P06', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P07001', '1', 'KAB. BOALEMO ', 'P07', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P07002', '1', 'KAB. BONE BOLANGO ', 'P07', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P07003', '1', 'KAB. GORONTALO ', 'P07', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P07004', '0', 'KOTA GORONTALO ', 'P07', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P07005', '1', 'KAB. GORONTALO UTARA ', 'P07', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P07006', '1', 'KAB. POHUWATO ', 'P07', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08001', '1', 'KAB. BATANG HARI ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08002', '1', 'KAB. BUNGO ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08003', '0', 'KOTA JAMBI ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08004', '1', 'KAB. KERINCI ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08005', '1', 'KAB. MERANGIN ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08006', '1', 'KAB. MUARO JAMBI ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08007', '1', 'KAB. SAROLANGUN ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08008', '0', 'KOTA SUNGAIPENUH ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08009', '1', 'KAB. TANJUNG JABUNG BARAT ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08010', '1', 'KAB. TANJUNG JABUNG TIMUR ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P08011', '1', 'KAB. TEBO ', 'P08', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09001', '0', 'KOTA BANDUNG ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09002', '1', 'KAB. BANDUNG ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09003', '1', 'KAB. BANDUNG BARAT ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09004', '0', 'KOTA BANJAR ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09005', '1', 'KAB. BEKASI ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09006', '0', 'KOTA BEKASI ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09007', '1', 'KAB. BOGOR ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09008', '0', 'KOTA BOGOR ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09009', '1', 'KAB. CIAMIS ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09010', '1', 'KAB. CIANJUR ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09011', '0', 'KOTA CIMAHI ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09012', '1', 'KAB. CIREBON ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09013', '0', 'KOTA CIREBON ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09014', '0', 'KOTA DEPOK ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09015', '1', 'KAB. GARUT ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09016', '1', 'KAB. INDRAMAYU ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09017', '1', 'KAB. KARAWANG ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09018', '1', 'KAB. KUNINGAN ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09019', '1', 'KAB. MAJALENGKA ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09020', '1', 'KAB. PANGANDARAN ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09021', '1', 'KAB. PURWAKARTA ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09022', '1', 'KAB. SUBANG ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09023', '1', 'KAB. SUKABUMI ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09024', '0', 'KOTA SUKABUMI ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09025', '1', 'KAB. SUMEDANG ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09026', '0', 'KOTA TASIKMALAYA ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P09027', '1', 'KAB. TASIKMALAYA ', 'P09', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10001', '1', 'KAB. BANJARNEGARA ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10002', '1', 'KAB. BANYUMAS ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10003', '1', 'KAB. BATANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10004', '1', 'KAB. BLORA ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10005', '1', 'KAB. BOYOLALI ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10006', '1', 'KAB. BREBES ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10007', '1', 'KAB. CILACAP ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10008', '1', 'KAB. DEMAK ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10009', '1', 'KAB. GROBOGAN ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10010', '1', 'KAB. JEPARA ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10011', '1', 'KAB. KARANGANYAR ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10012', '1', 'KAB. KEBUMEN ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10013', '1', 'KAB. KENDAL ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10014', '1', 'KAB. KLATEN ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10015', '1', 'KAB. KUDUS ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10016', '1', 'KAB. MAGELANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10017', '0', 'KOTA MAGELANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10018', '1', 'KAB. PATI ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10019', '1', 'KAB. PEKALONGAN ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10020', '0', 'KOTA PEKALONGAN ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10021', '1', 'KAB. PEMALANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10022', '1', 'KAB. PURBALINGGA ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10023', '1', 'KAB. PURWOREJO ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10024', '1', 'KAB. REMBANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10025', '0', 'KOTA SALATIGA ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10026', '1', 'KAB. SEMARANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10027', '0', 'KOTA SEMARANG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10028', '1', 'KAB. SRAGEN ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10029', '1', 'KAB. SUKOHARJO ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10030', '0', 'KOTA SURAKARTA (SOLO) ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10031', '1', 'KAB. TEGAL ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10032', '0', 'KOTA TEGAL ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10033', '1', 'KAB. TEMANGGUNG ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10034', '1', 'KAB. WONOGIRI ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P10035', '1', 'KAB. WONOSOBO ', 'P10', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11001', '1', 'KAB. BANGKALAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11002', '1', 'KAB. BANYUWANGI ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11003', '0', 'KOTA BATU ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11004', '1', 'KAB. BLITAR ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11005', '0', 'KOTA BLITAR ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11006', '1', 'KAB. BOJONEGORO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11007', '1', 'KAB. BONDOWOSO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11008', '1', 'KAB. GRESIK ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11009', '1', 'KAB. JEMBER ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11010', '1', 'KAB. JOMBANG ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11011', '1', 'KAB. KEDIRI ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11012', '0', 'KOTA KEDIRI ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11013', '1', 'KAB. LAMONGAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11014', '1', 'KAB. LUMAJANG ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11015', '1', 'KAB. MADIUN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11016', '0', 'KOTA MADIUN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11017', '1', 'KAB. MAGETAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11018', '1', 'KAB. MALANG ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11019', '0', 'KOTA MALANG ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11020', '1', 'KAB. MOJOKERTO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11021', '0', 'KOTA MOJOKERTO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11022', '1', 'KAB. NGANJUK ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11023', '1', 'KAB. NGAWI ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11024', '1', 'KAB. PACITAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11025', '1', 'KAB. PAMEKASAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11026', '1', 'KAB. PASURUAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11027', '0', 'KOTA PASURUAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11028', '1', 'KAB. PONOROGO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11029', '1', 'KAB. PROBOLINGGO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11030', '0', 'KOTA PROBOLINGGO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11031', '1', 'KAB. SAMPANG ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11032', '1', 'KAB. SIDOARJO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11033', '1', 'KAB. SITUBONDO ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11034', '1', 'KAB. SUMENEP ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11035', '0', 'KOTA SURABAYA ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11036', '1', 'KAB. TRENGGALEK ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11037', '1', 'KAB. TUBAN ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P11038', '1', 'KAB. TULUNGAGUNG ', 'P11', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12001', '1', 'KAB. BENGKAYANG ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12002', '1', 'KAB. KAPUAS HULU ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12003', '1', 'KAB. KAYONG UTARA ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12004', '1', 'KAB. KETAPANG ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12005', '1', 'KAB. KUBU RAYA ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12006', '1', 'KAB. LANDAK ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12007', '1', 'KAB. MELAWI ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12008', '1', 'KAB. PONTIANAK ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12009', '0', 'KOTA PONTIANAK ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12010', '1', 'KAB. SAMBAS ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12011', '1', 'KAB. SANGGAU ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12012', '1', 'KAB. SEKADAU ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12013', '0', 'KOTA SINGKAWANG ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P12014', '1', 'KAB. SINTANG ', 'P12', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13001', '1', 'KAB. BALANGAN ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13002', '1', 'KAB. BANJAR ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13003', '0', 'KOTA BANJARBARU ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13004', '0', 'KOTA BANJARMASIN ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13005', '1', 'KAB. BARITO KUALA ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13006', '1', 'KAB. HULU SUNGAI SELATAN ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13007', '1', 'KAB. HULU SUNGAI TENGAH ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13008', '1', 'KAB. HULU SUNGAI UTARA ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13009', '1', 'KAB. KOTABARU ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13010', '1', 'KAB. TABALONG ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13011', '1', 'KAB. TANAH BUMBU ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13012', '1', 'KAB. TANAH LAUT ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P13013', '1', 'KAB. TAPIN ', 'P13', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14001', '1', 'KAB. BARITO SELATAN ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14002', '1', 'KAB. BARITO TIMUR ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14003', '1', 'KAB. BARITO UTARA ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14004', '1', 'KAB. GUNUNG MAS ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14005', '1', 'KAB. KAPUAS ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14006', '1', 'KAB. KATINGAN ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14007', '1', 'KAB. KOTAWARINGIN BARAT ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14008', '1', 'KAB. KOTAWARINGIN TIMUR ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14009', '1', 'KAB. LAMANDAU ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14010', '1', 'KAB. MURUNG RAYA ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14011', '0', 'KOTA PALANGKA RAYA ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14012', '1', 'KAB. PULANG PISAU ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14013', '1', 'KAB. SERUYAN ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P14014', '1', 'KAB. SUKAMARA ', 'P14', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15001', '0', 'KOTA BALIKPAPAN ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15002', '1', 'KAB. BERAU ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15003', '0', 'KOTA BONTANG ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15004', '1', 'KAB. KUTAI BARAT ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15005', '1', 'KAB. KUTAI KARTANEGARA ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15006', '1', 'KAB. KUTAI TIMUR ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15007', '1', 'KAB. PASER ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15008', '1', 'KAB. PENAJAM PASER UTARA ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P15009', '0', 'KOTA SAMARINDA ', 'P15', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P16001', '1', 'KAB. BULUNGAN (BULONGAN) ', 'P16', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P16002', '1', 'KAB. MALINAU ', 'P16', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P16003', '1', 'KAB. NUNUKAN ', 'P16', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P16004', '1', 'KAB. TANA TIDUNG ', 'P16', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P16005', '0', 'KOTA TARAKAN ', 'P16', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17001', '0', 'KOTA BATAM ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17002', '1', 'KAB. BINTAN ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17003', '1', 'KAB. KARIMUN ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17004', '1', 'KAB. KEPULAUAN ANAMBAS ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17005', '1', 'KAB. LINGGA ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17006', '1', 'KAB. NATUNA ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P17007', '0', 'KOTA TANJUNG PINANG ', 'P17', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18001', '0', 'KOTA BANDAR LAMPUNG ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18002', '1', 'KAB. LAMPUNG BARAT ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18003', '1', 'KAB. LAMPUNG SELATAN ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18004', '1', 'KAB. LAMPUNG TENGAH ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18005', '1', 'KAB. LAMPUNG TIMUR ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18006', '1', 'KAB. LAMPUNG UTARA ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18007', '1', 'KAB. MESUJI ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18008', '0', 'KOTA METRO ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18009', '1', 'KAB. PESAWARAN ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18010', '1', 'KAB. PESISIR BARAT ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18011', '1', 'KAB. PRINGSEWU ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18012', '1', 'KAB. TANGGAMUS ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18013', '1', 'KAB. TULANG BAWANG ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18014', '1', 'KAB. TULANG BAWANG BARAT ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P18015', '1', 'KAB. WAY KANAN ', 'P18', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19001', '0', 'KOTA AMBON ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19002', '1', 'KAB. BURU ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19003', '1', 'KAB. BURU SELATAN ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19004', '1', 'KAB. KEPULAUAN ARU ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19005', '1', 'KAB. MALUKU BARAT DAYA ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19006', '1', 'KAB. MALUKU TENGAH ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19007', '1', 'KAB. MALUKU TENGGARA ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19008', '1', 'KAB. MALUKU TENGGARA BARAT ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19009', '1', 'KAB. SERAM BAGIAN BARAT ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19010', '1', 'KAB. SERAM BAGIAN TIMUR ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P19011', '0', 'KOTA TUAL ', 'P19', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20001', '1', 'KAB. HALMAHERA BARAT ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20002', '1', 'KAB. HALMAHERA SELATAN ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20003', '1', 'KAB. HALMAHERA TENGAH ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20004', '1', 'KAB. HALMAHERA TIMUR ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20005', '1', 'KAB. HALMAHERA UTARA ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20006', '1', 'KAB. KEPULAUAN SULA ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20007', '1', 'KAB. PULAU MOROTAI ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20008', '0', 'KOTA TERNATE ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P20009', '0', 'KOTA TIDORE KEPULAUAN ', 'P20', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21001', '1', 'KAB. ACEH BARAT ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21002', '1', 'KAB. ACEH BARAT DAYA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21003', '1', 'KAB. ACEH BESAR ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21004', '1', 'KAB. ACEH JAYA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21005', '1', 'KAB. ACEH SELATAN ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21006', '1', 'KAB. ACEH SINGKIL ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21007', '1', 'KAB. ACEH TAMIANG ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21008', '1', 'KAB. ACEH TENGAH ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21009', '1', 'KAB. ACEH TENGGARA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21010', '1', 'KAB. ACEH TIMUR ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21011', '1', 'KAB. ACEH UTARA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21012', '0', 'KOTA BANDA ACEH ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21013', '1', 'KAB. BENER MERIAH ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21014', '1', 'KAB. BIREUEN ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21015', '1', 'KAB. GAYO LUES ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21016', '0', 'KOTA LANGSA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21017', '0', 'KOTA LHOKSEUMAWE ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21018', '1', 'KAB. NAGAN RAYA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21019', '1', 'KAB. PIDIE ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21020', '1', 'KAB. PIDIE JAYA ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21021', '0', 'KOTA SABANG ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21022', '1', 'KAB. SIMEULUE ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P21023', '0', 'KOTA SUBULUSSALAM ', 'P21', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22001', '1', 'KAB. BIMA ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22002', '0', 'KOTA BIMA ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22003', '1', 'KAB. DOMPU ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22004', '1', 'KAB. LOMBOK BARAT ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22005', '1', 'KAB. LOMBOK TENGAH ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22006', '1', 'KAB. LOMBOK TIMUR ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22007', '1', 'KAB. LOMBOK UTARA ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22008', '0', 'KOTA MATARAM ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22009', '1', 'KAB. SUMBAWA ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P22010', '1', 'KAB. SUMBAWA BARAT ', 'P22', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23001', '1', 'KAB. ALOR ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23002', '1', 'KAB. BELU ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23003', '1', 'KAB. ENDE ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23004', '1', 'KAB. FLORES TIMUR ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23005', '1', 'KAB. KUPANG ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23006', '0', 'KOTA KUPANG ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23007', '1', 'KAB. LEMBATA ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23008', '1', 'KAB. MANGGARAI ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23009', '1', 'KAB. MANGGARAI BARAT ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23010', '1', 'KAB. MANGGARAI TIMUR ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23011', '1', 'KAB. NAGEKEO ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23012', '1', 'KAB. NGADA ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23013', '1', 'KAB. ROTE NDAO ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23014', '1', 'KAB. SABU RAIJUA ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23015', '1', 'KAB. SIKKA ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23016', '1', 'KAB. SUMBA BARAT ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23017', '1', 'KAB. SUMBA BARAT DAYA ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23018', '1', 'KAB. SUMBA TENGAH ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23019', '1', 'KAB. SUMBA TIMUR ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23020', '1', 'KAB. TIMOR TENGAH SELATAN ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P23021', '1', 'KAB. TIMOR TENGAH UTARA ', 'P23', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24001', '1', 'KAB. ASMAT ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24002', '1', 'KAB. BIAK NUMFOR ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24003', '1', 'KAB. BOVEN DIGOEL ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24004', '1', 'KAB. DEIYAI (DELIYAI) ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24005', '1', 'KAB. DOGIYAI ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24006', '1', 'KAB. INTAN JAYA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24007', '1', 'KAB. JAYAPURA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24008', '0', 'KOTA JAYAPURA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24009', '1', 'KAB. JAYAWIJAYA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24010', '1', 'KAB. KEEROM ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24011', '1', 'KAB. KEPULAUAN YAPEN (YAPEN WAROPEN) ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24012', '1', 'KAB. LANNY JAYA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24013', '1', 'KAB. MAMBERAMO RAYA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24014', '1', 'KAB. MAMBERAMO TENGAH ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24015', '1', 'KAB. MAPPI ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24016', '1', 'KAB. MERAUKE ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24017', '1', 'KAB. MIMIKA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24018', '1', 'KAB. NABIRE ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24019', '1', 'KAB. NDUGA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24020', '1', 'KAB. PANIAI ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24021', '1', 'KAB. PEGUNUNGAN BINTANG ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24022', '1', 'KAB. PUNCAK ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24023', '1', 'KAB. PUNCAK JAYA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24024', '1', 'KAB. SARMI ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24025', '1', 'KAB. SUPIORI ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24026', '1', 'KAB. TOLIKARA ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24027', '1', 'KAB. WAROPEN ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24028', '1', 'KAB. YAHUKIMO ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P24029', '1', 'KAB. YALIMO ', 'P24', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25001', '1', 'KAB. FAKFAK ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25002', '1', 'KAB. KAIMANA ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25003', '1', 'KAB. MANOKWARI ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25004', '1', 'KAB. MANOKWARI SELATAN ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25005', '1', 'KAB. MAYBRAT ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25006', '1', 'KAB. PEGUNUNGAN ARFAK ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25007', '1', 'KAB. RAJA AMPAT ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25008', '0', 'KOTA SORONG ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25009', '1', 'KAB. SORONG ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25010', '1', 'KAB. SORONG SELATAN ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25011', '1', 'KAB. TAMBRAUW ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25012', '1', 'KAB. TELUK BINTUNI ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P25013', '1', 'KAB. TELUK WONDAMA ', 'P25', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26001', '1', 'KAB. BENGKALIS ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26002', '0', 'KOTA DUMAI ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26003', '1', 'KAB. INDRAGIRI HILIR ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26004', '1', 'KAB. INDRAGIRI HULU ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26005', '1', 'KAB. KAMPAR ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26006', '1', 'KAB. KEPULAUAN MERANTI ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26007', '1', 'KAB. KUANTAN SINGINGI ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26008', '0', 'KOTA PEKANBARU ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26009', '1', 'KAB. PELALAWAN ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26010', '1', 'KAB. ROKAN HILIR ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26011', '1', 'KAB. ROKAN HULU ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P26012', '1', 'KAB. SIAK ', 'P26', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P27001', '1', 'KAB. MAJENE ', 'P27', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P27002', '1', 'KAB. MAMASA ', 'P27', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P27003', '1', 'KAB. MAMUJU ', 'P27', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P27004', '1', 'KAB. MAMUJU UTARA ', 'P27', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P27005', '1', 'KAB. POLEWALI MANDAR ', 'P27', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28001', '1', 'KAB. BANTAENG ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28002', '1', 'KAB. BARRU ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28003', '1', 'KAB. BONE ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28004', '1', 'KAB. BULUKUMBA ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28005', '1', 'KAB. ENREKANG ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28006', '1', 'KAB. GOWA ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28007', '1', 'KAB. JENEPONTO ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28008', '1', 'KAB. LUWU ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28009', '1', 'KAB. LUWU TIMUR ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28010', '1', 'KAB. LUWU UTARA ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28011', '0', 'KOTA MAKASSAR ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28012', '1', 'KAB. MAROS ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28013', '0', 'KOTA PALOPO ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28014', '1', 'KAB. PANGKAJENE KEPULAUAN ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28015', '0', 'KOTA PAREPARE ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28016', '1', 'KAB. PINRANG ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28017', '1', 'KAB. SELAYAR (KEPULAUAN SELAYAR) ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28018', '1', 'KAB. SIDENRENG RAPPANG/RAPANG ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28019', '1', 'KAB. SINJAI ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28020', '1', 'KAB. SOPPENG ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28021', '1', 'KAB. TAKALAR ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28022', '1', 'KAB. TANA TORAJA ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28023', '1', 'KAB. TORAJA UTARA ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P28024', '1', 'KAB. WAJO ', 'P28', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29001', '1', 'KAB. BANGGAI ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29002', '1', 'KAB. BANGGAI KEPULAUAN ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29003', '1', 'KAB. BUOL ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29004', '1', 'KAB. DONGGALA ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29005', '1', 'KAB. MOROWALI ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29006', '0', 'KOTA PALU ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29007', '1', 'KAB. PARIGI MOUTONG ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29008', '1', 'KAB. POSO ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29009', '1', 'KAB. SIGI ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29010', '1', 'KAB. TOJO UNA-UNA ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P29011', '1', 'KAB. TOLI-TOLI ', 'P29', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30001', '0', 'KOTA BAU-BAU ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30002', '1', 'KAB. BOMBANA ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30003', '1', 'KAB. BUTON ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30004', '1', 'KAB. BUTON UTARA ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30005', '0', 'KOTA KENDARI ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30006', '1', 'KAB. KOLAKA ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30007', '1', 'KAB. KOLAKA UTARA ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30008', '1', 'KAB. KONAWE ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30009', '1', 'KAB. KONAWE SELATAN ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30010', '1', 'KAB. KONAWE UTARA ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30011', '1', 'KAB. MUNA ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P30012', '1', 'KAB. WAKATOBI ', 'P30', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31001', '0', 'KOTA BITUNG ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31002', '1', 'KAB. BOLAANG MONGONDOW (BOLMONG) ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31003', '1', 'KAB. BOLAANG MONGONDOW SELATAN ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31004', '1', 'KAB. BOLAANG MONGONDOW TIMUR ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31005', '1', 'KAB. BOLAANG MONGONDOW UTARA ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31006', '1', 'KAB. KEPULAUAN SANGIHE ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31007', '1', 'KAB. KEPULAUAN SIAU TAGULANDANG BIARO (SITARO) ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31008', '1', 'KAB. KEPULAUAN TALAUD ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31009', '0', 'KOTA KOTAMOBAGU ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31010', '0', 'KOTA MANADO ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31011', '1', 'KAB. MINAHASA ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31012', '1', 'KAB. MINAHASA SELATAN ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31013', '1', 'KAB. MINAHASA TENGGARA ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31014', '1', 'KAB. MINAHASA UTARA ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P31015', '0', 'KOTA TOMOHON ', 'P31', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32001', '1', 'KAB. AGAM ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32002', '0', 'KOTA BUKITTINGGI ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32003', '1', 'KAB. DHARMASRAYA ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32004', '1', 'KAB. KEPULAUAN MENTAWAI ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32005', '1', 'KAB. LIMA PULUH KOTO/KOTA ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32006', '0', 'KOTA PADANG ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32007', '0', 'KOTA PADANG PANJANG ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32008', '1', 'KAB. PADANG PARIAMAN ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32009', '0', 'KOTA PARIAMAN ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32010', '1', 'KAB. PASAMAN ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32011', '1', 'KAB. PASAMAN BARAT ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32012', '0', 'KOTA PAYAKUMBUH ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32013', '1', 'KAB. PESISIR SELATAN ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32014', '0', 'KOTA SAWAH LUNTO ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32015', '1', 'KAB. SIJUNJUNG (SAWAH LUNTO SIJUNJUNG) ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32016', '1', 'KAB. SOLOK ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32017', '0', 'KOTA SOLOK ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32018', '1', 'KAB. SOLOK SELATAN ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P32019', '1', 'KAB. TANAH DATAR ', 'P32', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33001', '1', 'KAB. BANYUASIN ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33002', '1', 'KAB. EMPAT LAWANG ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33003', '1', 'KAB. LAHAT ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33004', '0', 'KOTA LUBUK LINGGAU ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33005', '1', 'KAB. MUARA ENIM ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33006', '1', 'KAB. MUSI BANYUASIN ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33007', '1', 'KAB. MUSI RAWAS ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33008', '1', 'KAB. OGAN ILIR ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33009', '1', 'KAB. OGAN KOMERING ILIR ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33010', '1', 'KAB. OGAN KOMERING ULU ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33011', '1', 'KAB. OGAN KOMERING ULU SELATAN ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33012', '1', 'KAB. OGAN KOMERING ULU TIMUR ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33013', '0', 'KOTA PAGAR ALAM ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33014', '0', 'KOTA PALEMBANG ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P33015', '0', 'KOTA PRABUMULIH ', 'P33', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34001', '1', 'KAB. ASAHAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34002', '1', 'KAB. BATU BARA ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34003', '0', 'KOTA BINJAI ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34004', '1', 'KAB. DAIRI ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34005', '1', 'KAB. DELI SERDANG ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34006', '0', 'KOTA GUNUNGSITOLI ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34007', '1', 'KAB. HUMBANG HASUNDUTAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34008', '1', 'KAB. KARO ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34009', '1', 'KAB. LABUHAN BATU ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34010', '1', 'KAB. LABUHAN BATU SELATAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34011', '1', 'KAB. LABUHAN BATU UTARA ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34012', '1', 'KAB. LANGKAT ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34013', '1', 'KAB. MANDAILING NATAL ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34014', '0', 'KOTA MEDAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34015', '1', 'KAB. NIAS ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34016', '1', 'KAB. NIAS BARAT ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34017', '1', 'KAB. NIAS SELATAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34018', '1', 'KAB. NIAS UTARA ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34019', '1', 'KAB. PADANG LAWAS ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34020', '1', 'KAB. PADANG LAWAS UTARA ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34021', '0', 'KOTA PADANG SIDEMPUAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34022', '1', 'KAB. PAKPAK BHARAT ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34023', '0', 'KOTA PEMATANG SIANTAR ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34024', '1', 'KAB. SAMOSIR ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34025', '1', 'KAB. SERDANG BEDAGAI ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34026', '0', 'KOTA SIBOLGA ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34027', '1', 'KAB. SIMALUNGUN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34028', '0', 'KOTA TANJUNG BALAI ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34029', '1', 'KAB. TAPANULI SELATAN ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34030', '1', 'KAB. TAPANULI TENGAH ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34031', '1', 'KAB. TAPANULI UTARA ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34032', '0', 'KOTA TEBING TINGGI ', 'P34', 1);
INSERT INTO `wilayah_kota_kab`(`kabid`, `tipe_kab_kota`, `kabupaten_kota`, `propid`, `status`) VALUES ('P34033', '1', 'KAB. TOBA SAMOSIR ', 'P34', 1);
