INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P01', 'BALI', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P02', 'BANGKA BELITUNG', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P03', 'BANTEN', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P04', 'BENGKULU', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P05', 'DI YOGYAKARTA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P06', 'DKI JAKARTA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P07', 'GORONTALO', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P08', 'JAMBI', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P09', 'JAWA BARAT', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P10', 'JAWA TENGAH', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P11', 'JAWA TIMUR', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P12', 'KALIMANTAN BARAT', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P13', 'KALIMANTAN SELATAN', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P14', 'KALIMANTAN TENGAH', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P15', 'KALIMANTAN TIMUR', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P16', 'KALIMANTAN UTARA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P17', 'KEPULAUAN RIAU', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P18', 'LAMPUNG', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P19', 'MALUKU', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P20', 'MALUKU UTARA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P21', 'NANGGROE ACEH DARUSSALAM (NAD)', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P22', 'NUSA TENGGARA BARAT (NTB)', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P23', 'NUSA TENGGARA TIMUR (NTT)', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P24', 'PAPUA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P25', 'PAPUA BARAT', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P26', 'RIAU', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P27', 'SULAWESI BARAT', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P28', 'SULAWESI SELATAN', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P29', 'SULAWESI TENGAH', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P30', 'SULAWESI TENGGARA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P31', 'SULAWESI UTARA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P32', 'SUMATERA BARAT', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P33', 'SUMATERA SELATAN', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P34', 'SUMATERA UTARA', 1, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('', '', 0, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('', '', 0, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('', '', 0, '');
INSERT INTO `wilayah_propinsi`(`propid`, `propinsi_desc`, `status`, `companyid`) VALUES ('P35', 'testing2', 0, '');
